namespace GameSvr{
  partial class TFrmServerValue
    {
        public System.Windows.Forms.Label Label1;
        public System.Windows.Forms.Label Label2;
        public System.Windows.Forms.Label Label3;
        public System.Windows.Forms.Label Label4;
        public System.Windows.Forms.Label Label5;
        public System.Windows.Forms.Label Label6;
        public System.Windows.Forms.Label Label7;
        public System.Windows.Forms.Label Label8;
        public System.Windows.Forms.Label Label9;
        public System.Windows.Forms.Label Label10;
        public System.Windows.Forms.NumericUpDown EHum;
        public System.Windows.Forms.NumericUpDown EMon;
        public System.Windows.Forms.NumericUpDown EZen;
        public System.Windows.Forms.NumericUpDown ESoc;
        public System.Windows.Forms.NumericUpDown ENpc;
        public System.Windows.Forms.Button BitBtn1;
        public System.Windows.Forms.NumericUpDown EDec;
        public System.Windows.Forms.NumericUpDown ECheckBlock;
        public System.Windows.Forms.NumericUpDown ESendBlock;
        public System.Windows.Forms.NumericUpDown EAvailableBlock;
        public System.Windows.Forms.NumericUpDown EGateLoad;
        public System.Windows.Forms.CheckBox CbViewHack;
        public System.Windows.Forms.CheckBox CkViewAdmfail;
        private System.ComponentModel.Container components = null;
        private System.Windows.Forms.ToolTip toolTip1 = null;

        // Clean up any resources being used.
        protected override void Dispose(bool disposing)
        {
            if(disposing)
            {
                if(components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

#region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.Resources.ResourceManager resources = new System.Resources.ResourceManager(this.GetType());
            this.components = new System.ComponentModel.Container();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.Label1 = new System.Windows.Forms.Label();
            this.Label2 = new System.Windows.Forms.Label();
            this.Label3 = new System.Windows.Forms.Label();
            this.Label4 = new System.Windows.Forms.Label();
            this.Label5 = new System.Windows.Forms.Label();
            this.Label6 = new System.Windows.Forms.Label();
            this.Label7 = new System.Windows.Forms.Label();
            this.Label8 = new System.Windows.Forms.Label();
            this.Label9 = new System.Windows.Forms.Label();
            this.Label10 = new System.Windows.Forms.Label();
            this.EHum = new System.Windows.Forms.NumericUpDown();
            this.EMon = new System.Windows.Forms.NumericUpDown();
            this.EZen = new System.Windows.Forms.NumericUpDown();
            this.ESoc = new System.Windows.Forms.NumericUpDown();
            this.ENpc = new System.Windows.Forms.NumericUpDown();
            this.BitBtn1 = new System.Windows.Forms.Button();
            this.EDec = new System.Windows.Forms.NumericUpDown();
            this.ECheckBlock = new System.Windows.Forms.NumericUpDown();
            this.ESendBlock = new System.Windows.Forms.NumericUpDown();
            this.EAvailableBlock = new System.Windows.Forms.NumericUpDown();
            this.EGateLoad = new System.Windows.Forms.NumericUpDown();
            this.CbViewHack = new System.Windows.Forms.CheckBox();
            this.CkViewAdmfail = new System.Windows.Forms.CheckBox();
            this.SuspendLayout();
            this.Location  = new System.Drawing.Point(502, 327);
            this.ClientSize  = new System.Drawing.Size(397, 229);
            this.Font  = new System.Drawing.Font("MS Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(1)));
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Name = "FrmServerValue";
            this.Text = "Adjust Server Settings";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.AutoScroll = true;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.Label1.Size  = new System.Drawing.Size(72, 13);
            this.Label1.Location  = new System.Drawing.Point(40, 16);
            this.Label1.Enabled = true;
            this.Label1.Name = "Label1";
            this.Label1.Text = "Hum Limit Time";
            this.Label2.Size  = new System.Drawing.Size(71, 13);
            this.Label2.Location  = new System.Drawing.Point(40, 40);
            this.Label2.Enabled = true;
            this.Label2.Name = "Label2";
            this.Label2.Text = "Mon Limit Time";
            this.Label3.Size  = new System.Drawing.Size(69, 13);
            this.Label3.Location  = new System.Drawing.Point(40, 64);
            this.Label3.Enabled = true;
            this.Label3.Name = "Label3";
            this.Label3.Text = "Zen Limit Time";
            this.Label4.Size  = new System.Drawing.Size(69, 13);
            this.Label4.Location  = new System.Drawing.Point(40, 88);
            this.Label4.Enabled = true;
            this.Label4.Name = "Label4";
            this.Label4.Text = "Soc Limit Time";
            this.Label5.Size  = new System.Drawing.Size(70, 13);
            this.Label5.Location  = new System.Drawing.Point(40, 136);
            this.Label5.Enabled = true;
            this.Label5.Name = "Label5";
            this.Label5.Text = "Npc Limit Time";
            this.Label6.Size  = new System.Drawing.Size(70, 13);
            this.Label6.Location  = new System.Drawing.Point(40, 112);
            this.Label6.Enabled = true;
            this.Label6.Name = "Label6";
            this.Label6.Text = "Dec Limit Time";
            this.Label7.Size  = new System.Drawing.Size(84, 13);
            this.Label7.Location  = new System.Drawing.Point(208, 40);
            this.Label7.Enabled = true;
            this.Label7.Name = "Label7";
            this.Label7.Text = "Check Block Size";
            this.Label8.Size  = new System.Drawing.Size(87, 13);
            this.Label8.Location  = new System.Drawing.Point(208, 16);
            this.Label8.Enabled = true;
            this.Label8.Name = "Label8";
            this.Label8.Text = "Socket Block Size";
            this.Label9.Size  = new System.Drawing.Size(73, 13);
            this.Label9.Location  = new System.Drawing.Point(208, 64);
            this.Label9.Enabled = true;
            this.Label9.Name = "Label9";
            this.Label9.Text = "Available Block";
            this.Label10.Size  = new System.Drawing.Size(97, 13);
            this.Label10.Location  = new System.Drawing.Point(200, 104);
            this.Label10.Enabled = true;
            this.Label10.Name = "Label10";
            this.Label10.Text = "Gate Load Test (KB)";
            ((System.ComponentModel.ISupportInitialize)(this.EHum)).BeginInit();
            this.EHum.Size  = new System.Drawing.Size(47, 22);
            this.EHum.Location  = new System.Drawing.Point(124, 13);
            this.EHum.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.EHumKeyPress);
            this.EHum.Enabled = true;
            this.EHum.TabIndex = 0;
            this.EHum.Name = "EHum";
            this.EHum.Value = 0;
            ((System.ComponentModel.ISupportInitialize)(this.EMon)).BeginInit();
            this.EMon.Size  = new System.Drawing.Size(47, 22);
            this.EMon.Location  = new System.Drawing.Point(124, 37);
            this.EMon.Enabled = true;
            this.EMon.TabIndex = 1;
            this.EMon.Name = "EMon";
            this.EMon.Value = 0;
            ((System.ComponentModel.ISupportInitialize)(this.EZen)).BeginInit();
            this.EZen.Size  = new System.Drawing.Size(47, 22);
            this.EZen.Location  = new System.Drawing.Point(124, 61);
            this.EZen.Enabled = true;
            this.EZen.TabIndex = 2;
            this.EZen.Name = "EZen";
            this.EZen.Value = 0;
            ((System.ComponentModel.ISupportInitialize)(this.ESoc)).BeginInit();
            this.ESoc.Size  = new System.Drawing.Size(47, 22);
            this.ESoc.Location  = new System.Drawing.Point(124, 85);
            this.ESoc.Enabled = true;
            this.ESoc.TabIndex = 3;
            this.ESoc.Name = "ESoc";
            this.ESoc.Value = 0;
            ((System.ComponentModel.ISupportInitialize)(this.ENpc)).BeginInit();
            this.ENpc.Size  = new System.Drawing.Size(47, 22);
            this.ENpc.Location  = new System.Drawing.Point(124, 133);
            this.ENpc.Enabled = true;
            this.ENpc.TabIndex = 5;
            this.ENpc.Name = "ENpc";
            this.ENpc.Value = 0;
            this.BitBtn1.Size  = new System.Drawing.Size(75, 25);
            this.BitBtn1.Location  = new System.Drawing.Point(296, 184);
            this.BitBtn1.Enabled = true;
            this.BitBtn1.Name = "BitBtn1";
            this.BitBtn1.Text = "OK";
            this.BitBtn1.TabIndex = 10;
            this.BitBtn1.BackColor = System.Drawing.SystemColors.Control;
            ((System.ComponentModel.ISupportInitialize)(this.EDec)).BeginInit();
            this.EDec.Size  = new System.Drawing.Size(47, 22);
            this.EDec.Location  = new System.Drawing.Point(124, 109);
            this.EDec.Enabled = true;
            this.EDec.TabIndex = 4;
            this.EDec.Name = "EDec";
            this.EDec.Value = 0;
            ((System.ComponentModel.ISupportInitialize)(this.ECheckBlock)).BeginInit();
            this.ECheckBlock.Size  = new System.Drawing.Size(59, 22);
            this.ECheckBlock.Location  = new System.Drawing.Point(308, 37);
            this.ECheckBlock.Enabled = true;
            this.ECheckBlock.TabIndex = 7;
            this.ECheckBlock.Name = "ECheckBlock";
            this.ECheckBlock.Value = 0;
            ((System.ComponentModel.ISupportInitialize)(this.ESendBlock)).BeginInit();
            this.ESendBlock.Size  = new System.Drawing.Size(59, 22);
            this.ESendBlock.Location  = new System.Drawing.Point(308, 13);
            this.ESendBlock.Enabled = true;
            this.ESendBlock.TabIndex = 6;
            this.ESendBlock.Name = "ESendBlock";
            this.ESendBlock.Value = 0;
            ((System.ComponentModel.ISupportInitialize)(this.EAvailableBlock)).BeginInit();
            this.EAvailableBlock.Size  = new System.Drawing.Size(59, 22);
            this.EAvailableBlock.Location  = new System.Drawing.Point(308, 61);
            this.EAvailableBlock.Enabled = true;
            this.EAvailableBlock.TabIndex = 8;
            this.EAvailableBlock.Name = "EAvailableBlock";
            this.EAvailableBlock.Value = 0;
            ((System.ComponentModel.ISupportInitialize)(this.EGateLoad)).BeginInit();
            this.EGateLoad.Size  = new System.Drawing.Size(71, 22);
            this.EGateLoad.Location  = new System.Drawing.Point(308, 101);
            this.EGateLoad.Enabled = true;
            this.EGateLoad.TabIndex = 9;
            this.EGateLoad.Name = "EGateLoad";
            this.EGateLoad.Value = 0;
            this.CbViewHack.Size  = new System.Drawing.Size(129, 17);
            this.CbViewHack.Location  = new System.Drawing.Point(40, 176);
            this.CbViewHack.CheckState = System.Windows.Forms.CheckState.Checked;
            this.CbViewHack.Enabled = true;
            this.CbViewHack.TabIndex = 11;
            this.CbViewHack.Name = "CbViewHack";
            this.CbViewHack.Text = "View 1100X message";
            this.CbViewHack.Checked = true;
            this.CkViewAdmfail.Size  = new System.Drawing.Size(177, 17);
            this.CkViewAdmfail.Location  = new System.Drawing.Point(40, 192);
            this.CkViewAdmfail.Enabled = true;
            this.CkViewAdmfail.TabIndex = 12;
            this.CkViewAdmfail.Name = "CkViewAdmfail";
            this.CkViewAdmfail.Text = "View Admission failure message";
            this.Controls.Add(Label1);
            this.Controls.Add(Label2);
            this.Controls.Add(Label3);
            this.Controls.Add(Label4);
            this.Controls.Add(Label5);
            this.Controls.Add(Label6);
            this.Controls.Add(Label7);
            this.Controls.Add(Label8);
            this.Controls.Add(Label9);
            this.Controls.Add(Label10);
            this.Controls.Add(EHum);
            this.Controls.Add(EMon);
            this.Controls.Add(EZen);
            this.Controls.Add(ESoc);
            this.Controls.Add(ENpc);
            this.Controls.Add(BitBtn1);
            this.Controls.Add(EDec);
            this.Controls.Add(ECheckBlock);
            this.Controls.Add(ESendBlock);
            this.Controls.Add(EAvailableBlock);
            this.Controls.Add(EGateLoad);
            this.Controls.Add(CbViewHack);
            this.Controls.Add(CkViewAdmfail);
            ((System.ComponentModel.ISupportInitialize)(this.EHum)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EMon)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EZen)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ESoc)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ENpc)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EDec)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ECheckBlock)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ESendBlock)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EAvailableBlock)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EGateLoad)).EndInit();
            this.ResumeLayout(false);
        }
#endregion

    }
}
